[project]
name = "above_the_rim"
version = "0.1.0"
description = "Above the Rim API"
dependencies = []

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
