CREATE TABLE  teams (
	"ID" INTEGER NOT NULL, 
	"SHORT" VARCHAR(3) NOT NULL, 
	"NAME" VARCHAR(50) NOT NULL, 
	PRIMARY KEY ("ID"), 
	UNIQUE ("SHORT"), 
	UNIQUE ("NAME")
);
CREATE TABLE games (
	"ID" INTEGER NOT NULL, 
	"HOME_TEAM_ID" INTEGER, 
	"VISITING_TEAM_ID" INTEGER, 
	"HOME_TEAM_SCORE" INTEGER, 
	"VISITING_TEAM_SCORE" INTEGER, 
	PRIMARY KEY ("ID"), 
	CONSTRAINT "fk_games_HOME_TEAM_ID_teams" FOREIGN KEY("HOME_TEAM_ID") REFERENCES teams ("ID"),
	CONSTRAINT "fk_games_VISITING_TEAM_ID_teams" FOREIGN KEY("VISITING_TEAM_ID") REFERENCES teams ("ID")
);
CREATE TABLE quarters (
	"ID" INTEGER NOT NULL, 
	"GAME_ID" INTEGER, 
	"QUARTERS" VARCHAR(50), 
	PRIMARY KEY ("ID"), 
	CONSTRAINT "fk_quarters_GAME_ID_games" FOREIGN KEY("GAME_ID") REFERENCES games ("ID")
);
