"""test: changed onupdate

Revision ID: 09c1464f5f61
Revises: 92cbd326e735
Create Date: 2025-04-15 08:48:32.906897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c1464f5f61'
down_revision: Union[str, None] = '92cbd326e735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_games_HOME_TEAM_ID_teams'), 'teams', ['HOME_TEAM_ID'], ['ID'], onupdate='SET NULL', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        # batch_op.drop_constraint(batch_op.f('fk_games_HOME_TEAM_ID_teams'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'teams', ['HOME_TEAM_ID'], ['ID'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
