"""init

Revision ID: ec85afe8ce04
Revises: 
Create Date: 2025-04-15 08:39:46.520473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec85afe8ce04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with open('migrations/init.sql') as file:
        op.execute(file.read())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_teams_SHORT'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_teams_NAME'), type_='unique')

    # ### end Alembic commands ###
